### ISSUE TITLE
namespace: please use DNS delegation

### ISSUE THREAD

**Issue by philips** [coreos/kpm#28]
This project looks great! I really appreciate the new approach.

One thing that I ask is that we not repeat the same mistake that the docker hub made making a default namespace that seems to be rooted in a single namespace: hub.kubespray.io.

The approach we are taking with the OCI Image format, that was taken with the appc format, and in the Go language is to use a DNS federated namespace that can be delegated. It is too early to say exactly how the OCI delegation will work but you can read about the appc delegation here: https://github.com/appc/spec/blob/master/spec/discovery.md

Happy to discuss further, I think this is really important work y'all are doing.

**Comment by ant31** [comment]
Thanks for sharing, it is very interesting point.
I think @bgrant0607 and @jackgr tried to alert me on this 'dockerhub' design issue. 

I'm completely open to discuss this further and find a good and secure way for the community to share their applications resources.

**Comment by philips** [comment]
We also prototyped another concept to tackle this delegation here: https://github.com/appc/abd

For security we decided that defaulting to using HTTPS was secure enough for a majority of the web. And if you don't trust the webs TLS infrastructure you can use an out of band shared public key.

**Comment by ant31** [comment]
I'm currently working on https://github.com/kubespray/kpm-registry so anyone can create its own kpm-service.  Users will be able to chose to self-host it or use kpm.kubespray.io

About dns delegation, I like the specs of ac-discovery.
Applied to KPM, the dependencies list of the manifest would look like:
```yaml
deploy:
  - ant31/myapp  # fetch the dependency from the default registry(configurable in the cli)
  - core.os:etcd # query https://core.os/?kpm-discovery=1 to get the package location
  - kpm.sh:anyppath/isworking/kpm-ui # query https://kpm.sh?kpm-discovery=1
```

Following spec
the pages should return meta tags in the format of:
`<meta name="kpm-package" content="package-name location-uri">` 
In example:
```html
<meta name="kpm-package" content=etcd "https://registry.kubespray.io/packages/coreos/etcd?version={version}" >
<meta name="kpm-package" content=etcd "https://storage.googleapis.com/kpm-bucket/etcd_{{version}}.tar.gz" >
```
One interesting advantage is that the package can be relocated somewhere else without breaking other packages dependencies and propose mirrors. 

Is this (short) description cover the issue you described ?

**Comment by ant31** [comment]
Its have been merged, 
Some documentation: https://github.com/kubespray/kpm/blob/master/docs/package-discovery.md

It's now possible to use namespaced packages in the dependency list or in the command line: 
e.g:  `kpm deploy kpm.sh/kpm-registry` will request `https://kpm.sh` to get the 'origin' of kpm-registry. 

`https://kpm.sh` contains the following meta tag:
```html
<meta name="kpm-package" content="kpm.sh/{name} https://api.kubespray.io/api/v1/packages/kubespray/{name}/pull">
```

**Comment by philips** [comment]
Cool! One thing that should be strongly considered is the use of well-known URLs instead of the meta stuff. At the time when we were doing AppC it was unclear if well-known was going to become used anywhere, then OIDC started using it. https://github.com/appc/spec/issues/160
