### ISSUE TITLE
Private Registry / Hub

### ISSUE THREAD

**Issue by microadam** [coreos/kpm#43]
This looks really interesting! I would be interested in testing it out, but I would like to do so with my own private hub / registry. Is the source for the registry / hub available at all? I can't see any instructions for running your own.

Thanks!

**Comment by ant31** [comment]
Hi, 
Yes you can run private registry, I'm going to document this part (and simplify installation process)

##### Production
`kpm deploy kubespray/kpm-registry --namespace kpm`
It create an etcd 3-node cluster and bind them to 3 newly created PVC (you have to create pv yourself)

##### Development and testing
you can run the the registry from the source:
```
python setup.py install 
gunicorn kpm.api.wsgi:app  --threads 3 -w 3  -b '0.0.0.0:5000'
```
It will connect to a localhost etcd on port 2379package: ant31/ghost (0.7.7) pushed


packages are stored in etcd in the path format:
/kpm/packages/{namespace}/{name}/{version} 


To use this private registry every command have a `-H host` option 
```
$ kpm push -H http://private-cluster:30958 
package: ant31/ghost (0.7.7) pushed

$ kpm list -H http://private-cluster:30958 
app          version    downloads
-----------  ---------  -----------
ant31/ghost  0.7.7      -
```


Another point that may interest you, I'm currently working on a way to mix public and private registries so you can store your private packages and still depend on public ones

**Comment by microadam** [comment]
excellent! Thanks for the detailed information :)
